### PR TITLE
[SDK-3990] Fix `PaginatedResult.next()` behaviour when no next page

### LINKED ISSUE #1542: `PaginatedResult.next()` is returning `undefined` instead of `null` when there's no next page
Per [TG4](https://sdk.ably.com/builds/ably/specification/main/features/#TG4) it's meant to return `null`, but it returns `undefined`.

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
It's meant to return `null`, not `undefined`. See commit messages for more details.

Resolves #1542.

### CODE REVIEW

File: ably.d.ts [hunk 1]
```diff
@@ -3460,13 +3460,13 @@ declare namespace Types {
      *
      * @param results - A function which, upon success, will be fulfilled with a page of results for message and presence history, stats, and REST presence requests. Upon failure, the function will be called with information about the error.
      */
-    next(results: paginatedResultCallback<T>): void;
+    next(results: StandardCallback<PaginatedResult<T> | null>): void;
```
Comment (owenpearson) [inline ably.d.ts:3463]: could this just be:
```suggestion
    next(results: paginatedResultCallback<T | null>): void;
```

**Review by owenpearson — APPROVED** [review]
