### PR TITLE
[ECO-4780] Fix `Connection closed` error when using `usePresence` hook

### LINKED ISSUE #1753: usePresence error - Uncaught (in promise) Error: Connection closed
When using `usePresence`, if I reload the page, I see the following error (with preserve log on) 

```
ably.js:260 Uncaught (in promise) Error: Connection closed
    at _ErrorInfo.fromValues (webpack-internal:///(app-pages-browser)/./node_modules/ably/build/ably.js:260:34)
    at Object.closed (webpack-internal:///(app-pages-browser)/./node_modules/ably/build/ably.js:3697:27)
    at WebSocketTransport.close (webpack-internal:///(app-pages-browser)/./node_modules/ably/build/ably.js:3749:52)
    at _ConnectionManager.closeImpl (webpack-internal:///(app-pages-browser)/./node_modules/ably/build/ably.js:5113:42)
    at _ConnectionManager.requestState (webpack-internal:///(app-pages-browser)/./node_modules/ably/build/ably.js:4898:12)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/ably/build/ably.js:4197:16)
```

I wonder if maybe ably-js is trying to send an event like "leave" but the connection is already closed? Possibly related to [this](https://github.com/ably/ably-js/blob/main/src/platform/react-hooks/src/hooks/usePresence.ts#L45) LOC?

The code to reproduce is very simple: 

```js
import { usePresence } from "ably/react"

const WhosOnlineList = ({ channelName }) => {

  usePresence(channelName, { fullName: Math.random() })


  return null
}
export default WhosOnlineList
```

Why does this matter?

It might not. I don't think you can technically be "present" on a channel if the connection has closed, but I'd like to understand the error better in case I should be structuring my React component differently. 

Thank you!

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4780) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by VeskeR**
Resolves #1753
Also seems to help with #1759 , ideally would confirm with the user that this fix helps with the problem once released.

`ably.connection.state` dependency in `onUnmount` callback caused the next issue:

When `ably.connection.state` is added as a dependency to the `onUnmount` callback, changes to the connection state will update this callback, which in turn triggers our mounting `useEffect` hook. This became problematic on page reloads: when the connection state changes to `closed`, the `onUnmount` callback updates, and this triggers our mounting `useEffect` hook, which calls `onMount` and tries to enter presence. Since the connection is closed at that point, we get a "Connection closed" error. Although it's not critical and doesn't seem to cause any application behavior issues, polluting the log with "Connection closed" errors should be avoided.

### CODE REVIEW

**Review by ttypic — APPROVED** [review]
Nice catch!

File: src/platform/react-hooks/src/hooks/usePresence.ts [hunk 1]
```diff
@@ -33,21 +33,33 @@ export function usePresence<T = any>(
...
   useEffect(() => {
     messageOrPresenceObjectRef.current = messageOrPresenceObject;
   }, [messageOrPresenceObject]);
 
+  useEffect(() => {
+    ablyConnectionStateRef.current = ably.connection.state;
+  }, [ably.connection.state]);
+
   const onMount = useCallback(async () => {
     await channel.presence.enter(messageOrPresenceObjectRef.current);
```
Comment (ttypic) [inline src/platform/react-hooks/src/hooks/usePresence.ts:54]: Maybe we should add checks for entering as well?

Comment (VeskeR) [reply src/platform/react-hooks/src/hooks/usePresence.ts:54]: That was my initial idea in order to fix this error, but I wasn't sure at a time that there is no situation where such a check might backfire. Like it won't try to enter a presence when connection is in a transitive state or something.
However, all of that comes down to [this check](https://github.com/ably/ably-js/blob/1753/fix-usePresence-connection-closed/src/common/lib/client/realtimepresence.ts#L133-L135) in `RealtimePresence._enterOrUpdateClient`. So basically, if we try to enter a presence and the connection is currently not active - we throw an error which would break everything in React anyway.
So I guess there is no downside to adding a check for connection state to that `onMount` method too.

Comment (VeskeR) [reply src/platform/react-hooks/src/hooks/usePresence.ts:54]: One more thing that came to mind:
With fix from this PR, what would happen now if we manually close connection and then open it again? Or that matter, if we loose connection to Able server due to network issues and then reconnect. Will we automatically rejoin presence set on reconnection?

Comment (VeskeR) [reply src/platform/react-hooks/src/hooks/usePresence.ts:54]: Since previously, the interaction between `ably.connection.state` in `useEffect` and our mounting hooks described in the [comment here](https://github.com/ably/ably-js/pull/1761/files#diff-63f026c2db9f54ace72a1df10dd2228a651f632b4d3f70594e6da465c5737786R36-R42) would actually benefit us.
On any connection state change that causes a re-render, we would leave and enter presence every time, thus guaranteeing that if the last connection state was active, we would be in the presence set.

I hope that makes sense 😅

Comment (VeskeR) [reply src/platform/react-hooks/src/hooks/usePresence.ts]: Updated to use `useConnectionStateListener` to monitor connection state changes and added inactive connection check in `useEffect` hook in https://github.com/ably/ably-js/compare/e295b6673c227be4f28ec8b1c575f985d2a9d1ef..78633ff8ccdca6e6e85a6ced8c5133d24187cdf1

File: src/platform/react-hooks/src/hooks/usePresence.ts [hunk 2]
```diff
@@ -44,19 +59,23 @@ export function usePresence<T = any>(
 
   const onUnmount = useCallback(() => {
     // if connection is in one of inactive states, leave call will produce exception
-    if (channel.state === 'attached' && !INACTIVE_CONNECTION_STATES.includes(ably.connection.state)) {
+    if (channel.state === 'attached' && !INACTIVE_CONNECTION_STATES.includes(connectionState)) {
       channel.presence.leave();
     }
-  }, [channel, ably.connection.state]);
+  }, [channel, connectionState]);
```
Comment (VeskeR) [inline src/platform/react-hooks/src/hooks/usePresence.ts:65]: Not sure about this dependency on `connectionState`. Seems like there is no way to avoid it.
Also, since this is a cleanup funciton, I think it would "lag behind" on the actual connection state, e.g. when connection state changes, we call `onUnmount` as our cleanup function in `useEffect` below, which has previous connection state stored (has stored `connected` value but the actual connection state is `closing` or something)

File: src/platform/react-hooks/src/hooks/usePresence.ts [hunk 3]
```diff
@@ -44,19 +59,23 @@ export function usePresence<T = any>(
...
 
   useEffect(() => {
+    if (INACTIVE_CONNECTION_STATES.includes(connectionState)) {
```
Comment (ttypic) [inline src/platform/react-hooks/src/hooks/usePresence.ts:68]: I would change this into:

```jsx
const shouldNotEnterPresence = INACTIVE_CONNECTION_STATES.includes(connectionState) || skip;

useEffect(() => {
   if (shouldNotEnterPresence) return;

   await channel.presence.enter(messageOrPresenceObjectRef.current);
   
   return () => {
      if (channel.state === 'attached' && !INACTIVE_CONNECTION_STATES.includes(connectionState)) {
        channel.presence.leave();
      }
   };
}, [shouldNotEnterPresence]);

```

this way we invoke effect only then it's necessary

**Review by ttypic — CHANGES_REQUESTED** [review]

File: src/platform/react-hooks/src/hooks/usePresence.ts (hunk 2 above)
Comment (VeskeR) [reply src/platform/react-hooks/src/hooks/usePresence.ts]: Agree, removed callbacks in https://github.com/ably/ably-js/compare/2743834c0521378015334b8d6af3de4b47058e03..2f9fadd5f8dc7fbc840e2e56f98b3340c721b808

File: src/platform/react-hooks/src/hooks/usePresence.ts (hunk 3 above)
Comment (VeskeR) [reply src/platform/react-hooks/src/hooks/usePresence.ts]: I liked the idea, thank you! Implemented it in https://github.com/ably/ably-js/compare/2743834c0521378015334b8d6af3de4b47058e03..2f9fadd5f8dc7fbc840e2e56f98b3340c721b808.

It works as expected, no "Connection closed" errors and now I finally can't see a problem with the solution. I hope that was the last change and we would be able to merge now.

File: src/platform/react-hooks/src/hooks/usePresence.ts [hunk 4]
```diff
@@ -26,37 +27,48 @@ export function usePresence<T = any>(
...
+      // here we use the ably.connection.state property, which upon this cleanup function call
+      // will have the current connection state for that connection, thanks to us accessing the Ably instance here by reference.
+      // if the connection is in one of the inactive states or the channel is not attached, a presence.leave call will produce an exception.
+      // so we only leave presence in other cases.
+      if (channel.state === 'attached' && !INACTIVE_CONNECTION_STATES.includes(ably.connection.state)) {
+        channel.presence.leave();
+      }
     };
-  }, [skip, onMount, onUnmount]);
+  }, [shouldNotEnterPresence, channel, ably.connection.state]);
```
Comment (ttypic) [inline src/platform/react-hooks/src/hooks/usePresence.ts:71]: let's put `ably` here instead of  `ably.connection.state` to avoid unnecessary effect remounts

**Review by ttypic — CHANGES_REQUESTED** [review]

File: src/platform/react-hooks/src/hooks/usePresence.ts (hunk 4 above)
Comment (VeskeR) [reply src/platform/react-hooks/src/hooks/usePresence.ts]: Updated

**Review by ttypic — APPROVED** [review]
LGTM
